Configured and refactoring on existing codes
wp-erp/wp-erp pull request #1221
Opened 2021-03-08 09:01 UTC by Rink9

-Created e2e folder & configured test formats
-Refactors for accounting existing codes

2021-08-16 08:22 UTC, FaraziF requested changes
Please review the feedback

2021-08-16 08:22 UTC, FaraziF commented on tests/e2e/core-tests/HRM/designation_01_addDesignation_test.js
> +Scenario('addDepartment', ({ I, loginAs}) => {
Scenario? designation or department

2021-08-18 05:03 UTC, Rink9 commented
@FaraziF FIXED all the issues.

2021-08-18 05:05 UTC, FaraziF approved these changes

2021-08-18 05:11 UTC, tanmayjay approved these changes

2021-08-18 05:12 UTC, merged