Fix #1193 - Transaction filter count quantity fixed based on status, …
wp-erp/wp-erp pull request #1226
Opened 2021-03-19 09:18 UTC by ManiruzzamanAkash

…type and customer

#### Changes proposed in this Pull Request:

#### Related issue(s):

2021-03-21 10:32 UTC, tanmayjay reviewed
Check if the same issue exists in other transactions, e.g. `purchase`, `expense`. If exists, fix those as well.

2021-03-21 10:32 UTC, tanmayjay commented on modules/accounting/api/class-rest-api-transactions.php
> +                'customer_id' => $args['customer_id']
Kindly include the date filters (`start_date` and `end_date`) as well.

2021-03-24 03:50 UTC, tanmayjay approved these changes

2021-03-29 05:36 UTC, Rink9 commented
@ManiruzzamanAkash
**Issues:**
**Sales:**
- After clicking the "cancel" button filter resets.
- After setting a particular date cant to be able to go "All" Type
- Filter can be minimized after clicking outside of the filter.
**Purchase:** 
- After clicking the "cancel" button filter resets.
- After setting a particular date cant to be able to go "All" Type
- Filter can be minimized after clicking outside of the filter.

2021-03-31 04:24 UTC, Rink9 commented
@ManiruzzamanAkash checked and approved.

2021-03-31 09:15 UTC, Rink9 commented
CRM:
**Issues:**
- Reset button doesn't work and also has design issues.

2021-04-02 06:56 UTC, tanmayjay approved these changes

2021-04-02 09:31 UTC, tanmayjay requested changes
Kindly update the requested changes

2021-04-02 12:12 UTC, tanmayjay approved these changes

2021-04-13 16:55 UTC, merged