Employee Education Result Feature
wp-erp/wp-erp pull request #1242
Opened 2021-04-21 09:43 UTC by ManiruzzamanAkash

[enhancement] Add Result feature in education tab. Add result and it's type(cgpa/gpa)

2021-05-03 14:56 UTC, tanmayjay approved these changes

2021-05-03 15:16 UTC, tanmayjay requested changes

2021-05-03 15:16 UTC, tanmayjay commented on includes/updates/update-1.8.3.php
> +                "ALTER TABLE `{$wpdb->prefix}erp_hr_education` ADD `result_type` ENUM('grade','percentage') NULL DEFAULT NULL AFTER `result`;"
Why this file changes exist in #1243 ?
On top of that the definitions are different!

2021-05-03 15:16 UTC, tanmayjay commented on modules/hrm/includes/functions-employee.php
> +}
Same function in #1243 with completely different definition

2021-05-03 15:16 UTC, tanmayjay commented on modules/hrm/views/js-templates/education-form.php
> +
Same changes in #1243 with different codes

2021-05-03 15:16 UTC, tanmayjay commented on includes/class-install.php
> +                `result_type` enum('grade', 'percentage') DEFAULT NULL,
Same thing with different schema exists in #1243

2021-05-03 18:11 UTC, ManiruzzamanAkash commented
Fixed redundant code issue on #1243

2021-05-05 04:29 UTC, tanmayjay approved these changes

2021-05-05 05:05 UTC, merged