Add Preset data for department and designation for initial installation
wp-erp/wp-erp pull request #1243
Opened 2021-04-22 05:24 UTC by ManiruzzamanAkash

[update] Added Preset data for department and designation for first time installation

2021-05-03 15:16 UTC, tanmayjay requested changes

2021-05-03 15:16 UTC, tanmayjay commented on includes/class-install.php
> +                `result_type` enum('gpa', 'cgpa') DEFAULT NULL,
Kindly check these changes exist in #1242 with different definition!

2021-05-03 15:16 UTC, tanmayjay commented on includes/updates/update-1.8.3.php
> +                "ALTER TABLE `{$wpdb->prefix}erp_hr_education` ADD `result_type` ENUM('cgpa','gpa') NULL DEFAULT NULL AFTER `result`;"
Kindly check these changes exist in #1242 with different definition!

2021-05-03 15:16 UTC, tanmayjay commented on modules/hrm/includes/functions-employee.php
> +}
```
function erp_hr_get_education_result_type_options( $selected = null ) {
    $types = [
        'grade'      => __( 'Grade',  'erp' ),
        'percentage' => __( 'Pecentage', 'erp' )
    ];

    $types = apply_filters( 'erp_hr_education_result_type_option', $types );

    if ( $selected ) {
        return ( isset( $types[ $selected ] ) ) ? $types[ $selected ] : '';
    }

    return $types;
}
```

Same function in #1242 with completely different definition

2021-05-03 15:16 UTC, tanmayjay commented on modules/hrm/includes/models/education.php
> +    protected $fillable = [ 'employee_id', 'school', 'degree', 'field', 'result', 'result_type', 'finished', 'notes', 'interest' ];
Changes from #1242

2021-05-03 15:16 UTC, tanmayjay commented on modules/hrm/views/js-templates/education-form.php
> +
Same changes from #1242  with different codes!

2021-05-03 18:10 UTC, ManiruzzamanAkash commented
Fixed redundant code in different PR.

2021-05-05 04:28 UTC, tanmayjay approved these changes

2021-05-05 05:07 UTC, merged